import { DELETE_MEMBER, EDIT_MEMBER, ADD_MEMBER, CHANGE_INFO } from './Types';
import mets from '../../Assets/images/mets.png';
import minev from '../../Assets/images/minev.png';
import quaday from '../../Assets/images/quaday.png';

const initState = {
  activeMember: {},
  addItem: {
    id: () => {Math.floor(Math.random() * 10000)},
    name: '',
    email: '',
    password: '',
    changePassword: '',
    Active: false,
    Supervisor: false,
    TeamChat: false,
    All: false,
    Email: false,
    Webchat: false,
    SMS: false,
    Facebook: false,
    Twitter: false,
  },
  members: [
    {
      id: 0,
      image: mets,
      name: 'Francesca Metts',
      email: 'gocare_info@gmail.com',
      password: '123456',
      changePassword: '',
      Active: true,
      Supervisor: false,
      TeamChat: true,
      All: false,
      Email: false,
      Webchat: false,
      SMS: true,
      Facebook: false,
      Twitter: true,
    },
    {
      id: 1,
      image: minev,
      name: 'Malcolm Quaday',
      email: 'gocare_info@gmail.com',
      password: '234567',
      changePassword: '',
      Active: false,
      Supervisor: true,
      TeamChat: true,
      All: true,
      Email: false,
      Webchat: true,
      SMS: false,
      Facebook: true,
      Twitter: true,
    },
    {
      id: 2,
      image: quaday,
      name: 'Lindsey Rivard',
      email: 'gocare_info@gmail.com',
      password: '345678',
      changePassword: '',
      Active: true,
      Supervisor: false,
      TeamChat: true,
      All: true,
      Email: true,
      Webchat: false,
      SMS: false,
      Facebook: false,
      Twitter: true,
    },
    {
      id: 3,
      image: mets,
      name: 'Francesca Metts',
      email: 'gocare_info@gmail.com',
      password: '456789',
      changePassword: '',
      Active: false,
      Supervisor: true,
      TeamChat: true,
      All: true,
      Email: false,
      Webchat: true,
      SMS: false,
      Facebook: true,
      Twitter: true,
    },
    {
      id: 4,
      image: minev,
      name: 'Malcolm Quaday',
      email: 'gocare_info@gmail.com',
      password: '5678910',
      changePassword: '',
      Active: true,
      Supervisor: false,
      TeamChat: false,
      All: true,
      Email: true,
      Webchat: false,
      SMS: false,
      Facebook: false,
      Twitter: true,
    },
    {
      id: 5,
      image: quaday,
      name: 'Lindsey Rivard',
      email: 'gocare_info@gmail.com',
      password: '67891011',
      changePassword: '',
      Active: false,
      Supervisor: true,
      TeamChat: false,
      All: true,
      Email: false,
      Webchat: true,
      SMS: false,
      Facebook: true,
      Twitter: false,
    },
    {
      id: 6,
      image: mets,
      name: 'Francesca Metts',
      email: 'gocare_info@gmail.com',
      password: '789101112',
      changePassword: '',
      Active: true,
      Supervisor: true,
      TeamChat: true,
      All: false,
      Email: true,
      Webchat: true,
      SMS: true,
      Facebook: false,
      Twitter: true,
    },
    {
      id: 7,
      image: minev,
      name: 'Malcolm Quaday',
      email: 'gocare_info@gmail.com',
      password: '8910111213',
      changePassword: '',
      Active: false,
      Supervisor: true,
      TeamChat: false,
      All: true,
      Email: false,
      Webchat: false,
      SMS: true,
      Facebook: true,
      Twitter: true,
    },
    {
      id: 8,
      image: quaday,
      name: 'Lindsey Rivard',
      email: 'gocare_info@gmail.com',
      password: '91011121314',
      changePassword: '',
      Active: true,
      Supervisor: true,
      TeamChat: true,
      All: false,
      Email: false,
      Webchat: false,
      SMS: true,
      Facebook: false,
      Twitter: true,
    },
    {
      id: 9,
      image: mets,
      name: 'Francesca Metts',
      email: 'gocare_info@gmail.com',
      password: '',
      changePassword: '1011121314',
      Active: false,
      Supervisor: true,
      TeamChat: false,
      All: true,
      Email: true,
      Webchat: false,
      SMS: false,
      Facebook: true,
      Twitter: false,
    },
    {
      id: 10,
      image: minev,
      name: 'Malcolm Quaday',
      email: 'gocare_info@gmail.com',
      password: '111213141516',
      changePassword: '',
      Active: true,
      Supervisor: false,
      TeamChat: true,
      All: false,
      Email: false,
      Webchat: true,
      SMS: true,
      Facebook: false,
      Twitter: false,
    },
    {
      id: 11,
      image: quaday,
      name: 'Lindsey Rivard',
      email: 'gocare_info@gmail.com',
      password: '1213141516',
      changePassword: '',
      Active: false,
      Supervisor: true,
      TeamChat: true,
      All: true,
      Email: false,
      Webchat: false,
      SMS: true,
      Facebook: true,
      Twitter: true,
    },
  ],
}

function compare(item, index, action) {
  if(item.id  === action.id ){
    Object.assign(item, action)
  }
  return item
}

export const ManageTableReducer = (state = initState, action) => {
  switch (action.type) {
    case EDIT_MEMBER:
      return {
        ...state,
        activeMember: state.members.filter((item,index) =>  index === action.payload)[0]
      };
    case DELETE_MEMBER:
      return {
        ...state,
        members: state.members.filter((item, index) => index !== action.payload),
      };
    case ADD_MEMBER:
      return {
        ...state,
        members: [].concat(state.members, [action.payload]),
      };
    case CHANGE_INFO:
      return {
        ...state,
        members: state.members.map((item, index) => compare(item, index, action.payload))
      };
    default:
      return state;
  }
};


